## 9.16일 문제 복습

In [5]:
#1
#9.14일 19번 문제

import re
li=[" ","1","12","123","1234","abc","1a"]
for string in li:
    print(re.sub(r"[0-9]?", "A",string), end=" ")

A A AA AAA AAAA AAAAA AaAbAcA AAaA 

In [9]:
#2
#9.16일 468 문제
#(1)

import numpy as np
a = np.arange(1,101).reshape((10, 10)) 
a[[4, 4, 7,7 ], [3,5,3,5]] 

array([44, 46, 74, 76])

In [13]:
#(2)

import numpy as np
x = np.arange(1, 101).reshape(10, 10)
x[4::3, 3:6:2] 

array([[44, 46],
       [74, 76]])

In [15]:
#기타 문제

import numpy as np
a = np.arange(1, 101).reshape(10, 10)
a[[0,1,2,3 ], [6,7,8,9]] 

array([ 7, 18, 29, 40])

In [20]:
#3. hello world만 출력.
#9.16 191번 문제

data = '''
  <head>
    <title>hello world</title>
  </head>
''' 
p = re.compile("(?<=>).+(?=<)")
p.findall(data)

['hello world']

In [24]:
data

'\n  <head>\n    <title>hello world</title>\n  </head>\n'

In [33]:
#4
#1~35로 구성된 6*6빙고판을 만들고 짝수만 출력하시오

a = np.arange(36).reshape(6,6)
a[:, 0::2] 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [40]:
#5
#1~35로 구성된 6*6빙고판을 만들고 홀수만 출력하시오

a = np.arange(36).reshape(6,6)
a[:,1::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [50]:
#6
#100로 구성된 100빙고판을 만들고 3차원 3행에 array를 출력하시오

a = np.arange(1,100).reshape(3,3,-1)
a

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]],

       [[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]],

       [[67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [51]:
a="hello python! i need python!"
a[-16:-8]

'! i need'

In [53]:
a="960101-1041111"
i = re.compile("(\d{6})[-](\d{7})")
li = i.findall(a)
for i in li:
    print(i)

('960101', '1041111')


In [95]:
key='축구:농구:배구:야구'
key.replace(':',"#")

'축구#농구#배구#야구'

In [57]:
a = {"apple" : "사과", "banana" : "바나나" , "cherry" : "체리" }
a["banana"]="포도"
a

{'apple': '사과', 'banana': '포도', 'cherry': '체리'}

In [74]:
sum=0

for i in range (1,4):
   sum = sum + i 
print(sum)    
    
    


6


In [77]:
list(map(lambda x : 3*x,[1,2,3,4,5]))

[3, 6, 9, 12, 15]

In [81]:
class FirstClass :
    def __init__(self, number):
        self.number = number
    
    def printNumber(self):
        return self.number
a = FirstClass(3)
print(a.printNumber())

3


In [82]:
numbers= [1,2,3,4,5]
a= []
for n in numbers:
    if n%2 ==1:
        a.append(n*2)
print(a) 

[2, 6, 10]


In [83]:
class Class_A :
    def func_A(self) :
        return 1
class Class_B(Class_A):
    def func_A(self):
        return 2
b = Class_B()
print(b.func_A())

2


In [230]:
data = '950302-355585'
import re
p = re.compile("\d{6}[-][34]\d{6}")
p.findall(data)
p

re.compile(r'\d{6}[-][34]\d{6}', re.UNICODE)

In [91]:
x= [1,-2, 3, 5, 8, -3]
list(map(lambda x:x>0,x))

[True, False, True, True, True, False]

In [231]:
a="960101-1041111"

### array

In [100]:
a=np.array([1,2,3,4])
print(a)
c= np.array([5,6])
c

[1 2 3 4]


array([5, 6])

In [103]:
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [106]:
np.array([[1],[2]])

array([[1],
       [2]])

### linspace

In [107]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [109]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

### ones

In [233]:
#1로 채워라
np.ones((2,3),dtype="int16")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

### zeros

In [234]:
#0으로 채워라
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 희소행렬

In [235]:
#sparse matrix (희소행렬)
'''
10*10: 대부분 0
3행 3열 부분 1 
5행 6열 부분 1 인 행렬 만들기
'''

zero = np.zeros((10,10))

zero[3,3] = 1
zero[5,6] = 1
zero 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [115]:
#모든 원소가 3인 10*10행렬을 만드시오.
a = np.ones((10,10))
a * 3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

### np.full()

In [117]:
np.full((10,10),3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

### np.identity()

In [118]:
#단위행렬.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.eye()

In [121]:
#행렬 맞지 않아도 나옴.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

### np.tile()

In [125]:
#잘 쓰는 함수아님
#3열 2번반복

a=np.array=[1,2,3]
np.tile(a,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### 복사하는 방법

In [127]:
a=[1,2,3,4]

In [128]:
b=a
b

[1, 2, 3, 4]

In [129]:
c=a.copy()

In [131]:
import copy
d=copy.copy(a)
d

[1, 2, 3, 4]

In [132]:
b[0]=100
b

[100, 2, 3, 4]

In [133]:
print(id(a))
print(id(b))
print(id(c))
print(id(d))

1646919817024
1646919817024
1646919634880
1646919147392


In [236]:
import numpy as np
a= np.array([1,2,3,4])
a

TypeError: 'list' object is not callable

In [227]:
import list

ModuleNotFoundError: No module named 'list'

In [137]:
#View

#### 문제{65}

In [237]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [238]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [141]:
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [142]:
#copy와 view의 차이는??

### 배열의 결합 stack
- vstack
- hstack 
- dstack

### vstack{68}

In [241]:
[0,10,20,30,40,50,60,70,80,90]

a=np.arange(10)*10
b=np.arange(10)*20

In [242]:
np.vstack((a,b))

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]])

### hstack{69}

In [243]:
np.hstack((a,b))

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90,   0,  20,  40,
        60,  80, 100, 120, 140, 160, 180])

In [244]:
np.hstack((a,b)).shape

(20,)

### dstack{70}

In [245]:
a=np.dstack([[1],[2],[3]])
a.shape
a

array([[[1, 2, 3]]])

In [246]:
b= np.dstack ( [ [1],[2],[3] ] )
b.shape
b

array([[[1, 2, 3]]])

In [248]:
#2차원
np.hstack((a,b))

array([[[1, 2, 3],
        [1, 2, 3]]])

In [247]:
#3차원
np.dstack((a,b))

array([[[1, 2, 3, 1, 2, 3]]])

## 배열의 분리 spliting
- 수평분리 hsplit
- 수직분리 vsplit

In [251]:
a=np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [172]:
np.hsplit(a,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [173]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

## 모양을 바꾸는 함수
- reshape
- flatten
- ravel

In [252]:
a=np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [253]:
a.shape

(4, 8)

In [254]:
a.size

32

In [255]:
#한줄로 쑥 나옴
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [181]:
a.flatten().shape

(32,)

In [182]:
#ravel은view 비슷하다.

## transpose 행과열의 위치를 바꾼다.
- a.T

In [187]:
a=np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [189]:
np.transpose(a)

array([[1, 3, 5],
       [2, 4, 6]])

#### 문제{83}

In [271]:
#1문제
#(1)

a = [1,2,3] 
b= [4,5,6]
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [272]:
#1문제
#(2)

a = np.array([1,2,3]) 
b= np.array([4,5,6])
np.hstack([a,b])


TypeError: 'list' object is not callable

In [266]:
#flatten,ravel의 차이는?

In [265]:
#3번 문제

a = np.arange(1,5).reshape(2,2)
a.T 

array([[1, 3],
       [2, 4]])

## 비교 정렬 comparison {84}

- 비교 comparison
- 정렬 sort
- 인덱싱 indexing

#### 문제{99}

In [296]:
# 문제 {99}

a = np.arange(6).reshape(1,-1)
b = np.arange(10,16).reshape(1,-1)
c = np.arange(20,26).reshape(1,-1)
d = np.arange(30,36).reshape(1,-1)
e = np.arange(40,46).reshape(1,-1)
f = np.arange(50,56).reshape(1,-1)
a=np.vstack((a,b,c,d,e,f)) 
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [295]:
# 문제 {99}

a = np.arange(6)
array = a.copy()
for i in range(5):
    i+=1
    array = np.vstack((array, a+10*i))
a=array 
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

### 팬시 인덱싱 fancy indexing{109}
:정수배열을 indexer로 사용해서 indexing하는 방법.

- position
- boolean
- condition

In [199]:
a=np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [200]:
a[[1,2,-3]]

array([10, 20, 50])

In [224]:
indices =[a,2,-3]
a[indices]

C:\Users\admin\AppData\Local\Temp\ipykernel_1392\3806105379.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a[indices]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [217]:
mask=[False,True,True,False,False,False,True,False,False,]
a[mask]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 9

In [223]:
mask = np.array[0,1,1,0,0,1,0,0], dtype=bool
a[mask]

TypeError: cannot unpack non-iterable type object

In [205]:
a = np.arange(25).reshape(5, 5)
a[[0, 1, 2, 3], [1, 2, 3, 4]] 

array([ 1,  7, 13, 19])

In [215]:
array([225,  81,   9,  64, 196])

array([81., 76., 73., 72., 73., 76.])

(array([2, 2, 2, 2, 2, 2, 3], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 0], dtype=int64)) 

TypeError: 'numpy.ndarray' object is not callable

In [214]:
array([225,  81,   9,  64, 196])
array([81., 76., 73., 72., 73., 76.])
array([9, 4, 1, 0, 1, 4, 9]) 

TypeError: 'numpy.ndarray' object is not callable

In [208]:
import numpy as np

### where {129}

In [213]:
a[np.where(a<10)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
#10보다 작은거 모두 0, 크거나 같으것 1로 바꾸자.
np.where(a < 10, 0, 1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 문제{104}

In [318]:
a = np.arange(6)
array = a.copy()
for i in range(5):
    i+=1
    array = np.vstack((array, a+10*i))
a=array 
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [319]:
#빨간색만 출력
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [321]:
#노란색출력
a[0,3:5]

array([3, 4])

In [322]:
#파란색출력
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [323]:
#파란칸 출력
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

#### 문제 {108}

In [304]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [311]:
#노란색 출력

a[4:,:]

array([[20, 21, 22, 23, 24]])

In [312]:
#빨간색 출력
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [316]:
#파란색 출력

a[1::2,:3:2]

array([[ 5,  7],
       [15, 17]])